format = """
[ ](#45475a)\
$os\
$username\
$hostname\
[](bg:#fab387 fg:#45475a)\
$directory\
[](fg:#fab387 bg:#8bd5ca)\
$git_branch\
$git_state\
$git_status\
[](fg:#8bd5ca bg:#7dc4e4)\
$c\
$java\
$nodejs\
$python\
$ruby\
$golang\
[](fg:#7dc4e4 bg:#b7bdf8)\
$docker_context\
[](fg:#b7bdf8 bg:#f0c6c6)\
$time\
[ ](fg:#f0c6c6)\
$cmd_duration\
$line_break\
$character"""

right_format = """$time"""


[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](purple)"

[cmd_duration]
disabled = false
format = "took [$duration]($style) "
style = "yellow"

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "
style = "fg:#11111b bg:#7dc4e4"
format = '[ $symbol ($version) ]($style)'

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " 󰌾"
style = "fg:#11111b bg:#fab387"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# style = "blue"
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[docker_context]
symbol = " "
style = "fg:#11111b bg:#b7bdf8"

[elixir]
symbol = " "
style = "fg:#11111b bg:#7dc4e4"

[elm]
symbol = " "
style = "fg:#11111b bg:#7dc4e4"

[fennel]
symbol = " "
style = "fg:#11111b bg:#7dc4e4"

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "
style = "fg:#11111b bg:#8bd5ca"
format = '[ $symbol $branch ]($style)'

[git_commit]
tag_symbol = '  '

[git_state]
# style = "bright-black"
style = "fg:#11111b bg:#8bd5ca"
format = '\([$state( $progress_current/$progress_total)]($style)\) '


[git_status]
# style = "cyan"
style = "bold fg:#d20f39 bg:#8bd5ca"
# format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
format = '([$all_status$ahead_behind ]($style))'
conflicted = "=​"
untracked = "?​"
modified = "!​"
staged = "+​"
renamed = "​»"
deleted = "✘​"
stashed = "≡"

[golang]
symbol = " "
style = "fg:#11111b bg:#7dc4e4"
format = '[ $symbol ($version) ]($style)'

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "
style = "fg:#cdd6f4 bg:#45475a"
format = '[$ssh_symbol$hostname]($style) in '


[java]
symbol = " "
style = "fg:#11111b bg:#7dc4e4"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "fg:#11111b bg:#7dc4e4"
format = '[ $symbol ($version) ]($style)'

[kotlin]
symbol = " "
style = "fg:#11111b bg:#7dc4e4"

[lua]
symbol = " "
style = "fg:#11111b bg:#7dc4e4"

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
style = "fg:#11111b bg:#7dc4e4"
format = '[ $symbol ($version) ]($style)'

[ocaml]
symbol = " "

[os]
style = "fg:#cdd6f4 bg:#45475a"
disabled = false # Disabled by default

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "
style = "fg:#11111b bg:#7dc4e4"

[php]
symbol = " "
style = "fg:#11111b bg:#7dc4e4"
format = '[ $symbol ($version) ]($style)'

[pijul_channel]
symbol = " "

[python]
symbol = " "
# style = "bright-black"
style = "fg:#11111b bg:#7dc4e4"
format = '[ ${symbol}${pyenv_prefix} (${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = true

[rlang]
symbol = "󰟔 "
format = '[ $symbol ($version)]($style)'

[ruby]
symbol = " "
# style = "bright-black"
style = "fg:#11111b bg:#7dc4e4"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = " "
style = "fg:#11111b bg:#7dc4e4"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "fg:#11111b bg:#7dc4e4"
format = '[ $symbol ($version) ]($style)'

[swift]
symbol = " "
style = "fg:#11111b bg:#7dc4e4"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#11111b bg:#f0c6c6"
format = '[ ⏰ $time ]($style)'

[username]
show_always = true
style_user = "fg:#cdd6f4 bg:#45475a"
style_root = "fg:#cdd6f4 bg:#45475a"
format = '[$user ]($style)'
disabled = false

[zig]
symbol = " "
